// <auto-generated />
namespace Hengrui.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class proficient2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(proficient2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711210736034_proficient-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
